language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - build-essential
      - libatlas-base-dev
      - gfortran

sudo: false

install:
  - pip install cython
  - pip install scipy==0.9
  - pip install scikit-learn==0.17
  - pip install numpy==1.10.4
  - pip install matplotlib==1.5.1
  - make

script:
  - make test
